// <auto-generated />
using System;
using BahiaImperial_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BahiaImperial_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504133432_Teste")]
    partial class Teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BahiaImperial_API.Models.BankAccounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<decimal>("LoanLimit")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Cpf_Cnpj");

                    b.ToTable("accounts", (string)null);

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BahiaImperial_API.Models.Client", b =>
                {
                    b.Property<string>("Cpf_Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Cpf_Cnpj");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("BahiaImperial_API.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasPrecision(3)
                        .HasColumnType("timestamp");

                    b.Property<decimal>("Current_Loan")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("Initial_Loan")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("Loan_Status")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("BahiaImperial_API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("TrDate")
                        .HasPrecision(3)
                        .HasColumnType("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("BahiaImperial_API.Models.User", b =>
                {
                    b.Property<string>("Cpf_Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<int>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Cpf_Cnpj");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BahiaImperial_API.Models.BankAccounts.Business", b =>
                {
                    b.HasBaseType("BahiaImperial_API.Models.BankAccounts.Account");

                    b.HasDiscriminator().HasValue("business");
                });

            modelBuilder.Entity("BahiaImperial_API.Models.BankAccounts.Checking", b =>
                {
                    b.HasBaseType("BahiaImperial_API.Models.BankAccounts.Account");

                    b.HasDiscriminator().HasValue("checking");
                });

            modelBuilder.Entity("BahiaImperial_API.Models.BankAccounts.Saving", b =>
                {
                    b.HasBaseType("BahiaImperial_API.Models.BankAccounts.Account");

                    b.HasDiscriminator().HasValue("saving");
                });

            modelBuilder.Entity("BahiaImperial_API.Models.BankAccounts.Account", b =>
                {
                    b.HasOne("BahiaImperial_API.Models.User", null)
                        .WithMany("Accounts")
                        .HasForeignKey("Cpf_Cnpj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BahiaImperial_API.Models.Client", b =>
                {
                    b.HasOne("BahiaImperial_API.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("BahiaImperial_API.Models.Client", "Cpf_Cnpj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BahiaImperial_API.Models.Loan", b =>
                {
                    b.HasOne("BahiaImperial_API.Models.BankAccounts.Account", null)
                        .WithMany("Loans")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BahiaImperial_API.Models.Transaction", b =>
                {
                    b.HasOne("BahiaImperial_API.Models.BankAccounts.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BahiaImperial_API.Models.BankAccounts.Account", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BahiaImperial_API.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
